pipeline:
  name: "Pet Clinic "
  identifier: Pet_Clinic
  projectIdentifier: SN_Project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build_Test
        identifier: Build_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build and Test
                  identifier: Build_and_Test
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean test -Dmaven.ext.class.path=
  properties:
    ci:
      codebase:
        connectorRef: Pet_Clinic
        build: <+input>
