pipeline:
  name: "Pet Clinic "
  identifier: Pet_Clinic
  projectIdentifier: SN_Project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build_Test
        identifier: Build_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build and Test
                  identifier: Build_and_Test
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.6-eclipse-temurin-17
                    shell: Sh
                    command: mvn clean package -DskipTests -Dcheckstyle.skip=true -Dnohttp.skip=true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - target/surefire-reports/*.xml
          sharedPaths:
            - /harness/.m2
    - stage:
        name: Node_Cache
        identifier: Node_Cache
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Clone Node Repo
                  identifier: Clone_Node_Repo
                  spec:
                    connectorRef: GitHub_Generic
                    cloneDirectory: /harness/node-app
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: npm install
                  identifier: npm_install
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18-alpine
                    shell: Sh
                    command: |-
                      cd /harness/node-app
                      npm install
          sharedPaths:
            - /harness/.npm
            - /harness/node_modules
            - /harness/.cache
  properties:
    ci:
      codebase:
        connectorRef: Pet_Clinic
        build: <+input>
