pipeline:
  name: PetClinic_SubTask3_Node.js
  identifier: PetClinic_SubTask3_Nodejs
  projectIdentifier: SN_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Nodejs_task_3
        build: <+input>
  stages:
    - stage:
        name: Node.js _Stage
        identifier: Nodejs__Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: Nodejs_Clone
                  identifier: Nodejs_Clone
                  spec:
                    connectorRef: Nodejs_task_3
                    cloneDirectory: /harness/node-app
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: npm install
                  identifier: npm_install
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18-alpine
                    shell: Sh
                    command: |-
                      cd /harness/node-app
                      npm install
